### ISSUE TITLE
se debe ocultar informacion sensible en los logs

### ISSUE THREAD

**Issue by juansmolano** [nebulae-tpi/emi#2]
Se debe eliminar las impresiones de login y pronipalmente la info del aobjeto de authenticacion con kleycloak
![screen shot 2019-02-11 at 9 57 37 am](https://user-images.githubusercontent.com/8793032/52571428-8b55e880-2de3-11e9-9cd4-46133400b79e.png)

**Comment by jestebanzapata** [comment]
Se eliminaron estos logs
